<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-L4O1C8HM" ignored="1" name="Command line test" tests="7" failures="1" timestamp="2022-07-18T00:27:04 IST" time="0.062" errors="0">
  <testcase name="getCredentials" time="0.005" classname="testClasses.DataProviderTest"/>
  <testcase name="getCredentials" time="0.0" classname="testClasses.DataProviderTest"/>
  <testcase name="getCredentials" time="0.0" classname="testClasses.DataProviderTest"/>
  <testcase name="testCase3" time="0.003" classname="testClasses.TestAnnotationAttributes">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at testClasses.TestAnnotationAttributes.testCase3(TestAnnotationAttributes.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testCase3 -->
  <testcase name="testCase4" time="0.0" classname="testClasses.TestAnnotationAttributes">
    <skipped/>
  </testcase> <!-- testCase4 -->
  <testcase name="testCase2" time="0.001" classname="testClasses.TestAnnotationAttributes"/>
  <testcase name="testCase1" time="0.001" classname="testClasses.TestAnnotationAttributes"/>
  <testcase name="testCase5" time="0.0" classname="testClasses.TestAnnotationAttributes">
    <ignored/>
  </testcase> <!-- testCase5 -->
</testsuite> <!-- Command line test -->
